# Generated by Django 3.2.4 on 2021-07-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210715_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
